version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./ProjectCritique.db:/app/ProjectCritique.db
      - ./static/abstracts:/app/static/abstracts
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
